name: flavofleet_main
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  cloud_firestore: ^4.7.0
  connectivity_plus: ^4.0.2
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.10.1
  firebase_core: ^2.17.0
  firebase_storage: ^11.2.0
  flutter:
    sdk: flutter
  flutter_stripe: ^9.3.0
  get: ^4.6.5
  google_sign_in: ^6.1.5
  http: null
  intl: ^0.18.1
  path_provider: ^2.1.1
  persistent_bottom_nav_bar: ^5.0.2
  shared_preferences: null
  uuid: ^3.0.7

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  image_path: "assets/image/playstore.png"

flutter:

  uses-material-design: true

  assets:
    - assets/image/food8.jpg
    - assets/image/food6.jpg
    - assets/image/google.png
    - assets/image/fb.jpg
    - assets/image/mainlogo.png
    - assets/image/foodLoading.jpg
    - assets/image/google-logo.png
    - assets/image/login_image.jpg
    - assets/image/splashImage.png
    - assets/image/location.png
    - assets/image/playstore.png

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900
