import 'package:flutter/material.dart';

class PrivacyPolicyPage extends StatelessWidget {
  const PrivacyPolicyPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Privacy Policy'),
      ),
      body: const SingleChildScrollView(
        padding: EdgeInsets.all(16),
        child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
          Text(
            'Privacy Policy',
            style: TextStyle(fontWeight: FontWeight.bold, fontSize: 18),
          ),
          SizedBox(height: 8),
          Text('Last updated: August 02, 2023'),
          SizedBox(height: 16),
          Text(
            'This Privacy Policy describes Our policies and procedures on the collection, '
            'use and disclosure of Your information when You use the Service and tells You '
            'about Your privacy rights and how the law protects You.',
          ),
          SizedBox(height: 16),
          Text(
            'Interpretation and Definitions',
            style: TextStyle(fontWeight: FontWeight.bold, fontSize: 18),
          ),
          SizedBox(height: 8),
          Text(
            'Interpretation',
            style: TextStyle(fontWeight: FontWeight.bold),
          ),
          Text(
            'The words of which the initial letter is capitalized have meanings defined '
            'under the following conditions. The following definitions shall have the same '
            'meaning regardless of whether they appear in singular or in plural.',
          ),
          SizedBox(height: 8),
          Text(
            'Definitions',
            style: TextStyle(fontWeight: FontWeight.bold),
          ),
          Text(
            'For the purposes of this Privacy Policy:\n'
            '  • Account means a unique account created for You to access our Service or parts of our Service.\n'
            '  • Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.\n'
            '  • Application refers to Flavor fleet, the software program provided by the Company.\n'
            '  • Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Flavor fleet.\n'
            '  • Country refers to: Kerala, India\n'
            '  • Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.\n'
            '  • Personal Data is any information that relates to an identified or identifiable individual.\n'
            '  • Service refers to the Application.\n'
            '  • Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.\n'
            '  • Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).\n'
            '  • You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.',
          ),
          SizedBox(height: 16),
          Text(
            'Collecting and Using Your Personal Data',
            style: TextStyle(fontWeight: FontWeight.bold, fontSize: 18),
          ),
          SizedBox(height: 8),
          Text(
            'Types of Data Collected',
            style: TextStyle(fontWeight: FontWeight.bold),
          ),
          SizedBox(height: 8),
          Text(
            'Personal Data',
            style: TextStyle(fontWeight: FontWeight.bold),
          ),
          Text(
            'While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You.\n'
            'Personally identifiable information may include, but is not limited to:\n'
            '  • Email address\n'
            '  • First name and last name\n'
            '  • Phone number\n'
            '  • Address, State, Province, ZIP/Postal code, City\n'
            '  • Usage Data',
          ),
        ]),
      ),
    );
  }
}
